# Generated by Django 4.1.5 on 2024-08-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdetail',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='farmerdetail',
            name='location',
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerdetail',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
