# Generated by Django 4.1.5 on 2024-08-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('outlet', 'outlet')], max_length=10),
        ),
    ]
