# Generated by Django 4.1.5 on 2024-11-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eschool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
